safe: true
lsi: false
pygments: true
name: "RORLab Podcast"
description: A podcast RORLab
url: http://rorlabpodcasts.github.io/
rorlab_url: http://rorlab.org/
sns: 
  twitter: https://twitter.com/rorlab
  facebook: https://www.facebook.com/groups/rubyonrailskorea
podcast:
  feed_url: http://rorlabpodcasts.github.io/podcast.xml
  copyright: 2013 RORLab
  author: "RORLab"
  keyword: "podcast,tech,rorlab,ruby,rails,ror,web,design"
  subtitle: Ruby On Rails Screencast
  owner_name: ChangHoon Jeong
  owner_email: iamseapy@gmail.com
  description: "A podcast from RORLab, Ruby On Rails for newbie."
  image: http://rorlabpodcasts.github.io/images/rorlab-logo-1400.png